# Generated by Django 4.1 on 2022-08-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feednews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='agency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='feednews.agency'),
        ),
    ]
