# Generated by Django 4.1 on 2022-08-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feednews', '0004_alter_news_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('createdate',)},
        ),
    ]
